"""create table cupom

Revision ID: 18906c26295c
Revises: 5607bc60977c
Create Date: 2022-07-25 22:48:42.822618

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '18906c26295c'
down_revision = '5607bc60977c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cupoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupoms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cupoms_name'), ['name'], unique=True)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cupoms_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_carts_cupoms_id'), ['cupoms_id'], unique=False)
        batch_op.create_foreign_key(None, 'cupoms', ['cupoms_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_carts_cupoms_id'))
        batch_op.drop_column('cupoms_id')

    with op.batch_alter_table('cupoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupoms_name'))
        batch_op.drop_index(batch_op.f('ix_cupoms_id'))

    op.drop_table('cupoms')
    # ### end Alembic commands ###
